linters:
  rubocop:
    display_cop_names: true
    config: './rubocop.yml'
files:
  ignore:
    - "bin/*"
    - "db/*"
    - "config/*"
    - "Guardfile"
    - "Rakefile"
    - "test/**/*"
    - "test/*"